### ISSUE TITLE
ModuleNotFoundError: No module named 'gentle'

### ISSUE THREAD

**Issue by zf223669** [ai4r/SGToolkit#1]
Dear sir:
    when I was installing the SGToolkit, when i typed the ./install.sh  ,it runned by a error, detail below:
./install.sh field cannot be recognized as the name of a cmdlet, function, script file, or runnable program. Check the spelling of the name, and if paths are included, make sure the path is correct, then try again.
Position line :1 Character :1
+ ./install.sh
+ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
+ CategoryInfo: ObjectNotFound: (./install.sh:String) [], CommandNotFoundException
+ FullyQualifiedErrorId: CommandNotFoundException

**The second error is:**
ERROR: Could not find a version that satisfies the requirement dataclasses==0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.8

How could i fix it? 
thank you !

**Comment by zf223669** [comment]
I am in the windows 10

**Comment by youngwoo-yoon** [comment]
Hello,
Gentle does not work in Windows. There are some related issues in the gentle repository: https://github.com/lowerquality/gentle. 
You could try WSL2 in Windows 10.
