### ISSUE TITLE
Need to install `gfortran` to install `gentle`

### ISSUE THREAD

**Issue by KeunwooPark** [ai4r/SGToolkit#10]
Hi.

I found out that gfortran is needed to install gentle ([ref](https://github.com/lowerquality/gentle/issues/194#issuecomment-493305958)).
`sudo apt install gfortran`

This is not particularly related to SGToolkit, but this fact would be helpful to others.

**Comment by youngwoo-yoon** [comment]
Thanks! I'll update the installation guide.
