### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by ireneb612** [ai4r/SGToolkit#4]
I got this error:

loading checkpoint /content/drive/MyDrive/Gesture-Generation-from-Trimodal-Context/SGToolkit/sg_core/output/sgtoolkit/multimodal_context_checkpoint_best.bin
{'config': '../config/multimodal_context_toolkit.yml', 'name': 'multimodal_context', 'train_data_path': '../data/ted_dataset_2020.07/lmdb_train', 'val_data_path': '../data/ted_dataset_2020.07/lmdb_val', 'test_data_path': '../data/ted_dataset_2020.07/lmdb_test', 'model_save_path': '../output/temp', 'pose_representation': '3d_vec', 'pose_norm_stats_path': None, 'pose_representation_path': None, 'mean_dir_vec': [[-0.00225], [-0.98496], [0.16212], [0.01831], [-0.79641], [0.52568], [0.02496], [-0.65216], [-0.67807], [-0.87815], [0.40211], [-0.06526], [-0.38831], [0.85245], [0.13283], [0.35888], [-0.16606], [0.7072], [0.87728], [0.41491], [-0.00166], [0.38441], [0.85739], [0.14593], [-0.39277], [-0.17973], [0.69081]], 'mean_pose': [[-0.0], [-2e-05], [4e-05], [-0.00055], [-0.24976], [0.03882], [0.00152], [-0.32251], [0.10291], [0.0043], [-0.43652], [0.02527], [-0.12537], [-0.19055], [0.03108], [-0.23547], [0.04413], [0.06726], [-0.14551], [0.00403], [0.23596], [0.12585], [-0.18445], [0.04031], [0.23547], [0.04749], [0.08014], [0.13293], [0.00299], [0.24744]], 'style_val_max': [[0.01574225], [1.5461352], [1.0]], 'style_val_mean': [[0.00241791], [0.48645255], [0.0]], 'style_val_std': [[0.00120855], [0.17992376], [1.0]], 'random_seed': 0, 'save_result_video': True, 'wordembed_path': '../data/fasttext/crawl-300d-2M-subword.bin', 'wordembed_dim': 300, 'freeze_wordembed': False, 'model': 'multimodal_context', 'epochs': 80, 'batch_size': 128, 'dropout_prob': 0.3, 'n_layers': 4, 'hidden_size': 300, 'residual_output': False, 'z_type': 'style_vector', 'input_context': 'both', 'use_pose_control': True, 'use_style_control': True, 'motion_resampling_framerate': 15, 'n_poses': 60, 'n_pre_poses': 30, 'subdivision_stride': 20, 'normalize_motion_data': True, 'augment_data': False, 'loader_workers': 4, 'GAN_noise_size': 0, 'diff_augment': True, 'learning_rate': 0.0005, 'discriminator_lr_weight': 0.2, 'loss_l1_weight': 500.0, 'loss_gan_weight': 5.0, 'loss_reg_weight': 0.05, 'loss_warmup': 10, 'eval_net_path': '../output/h36m_gesture_autoencoder/gesture_autoencoder_checkpoint_best.bin'}
Traceback (most recent call last):
  File "waitress_server.py", line 4, in <module>
    serve(app.app, host='0.0.0.0', port=8080)
  File "/usr/local/lib/python3.7/dist-packages/waitress/__init__.py", line 12, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.7/dist-packages/waitress/server.py", line 88, in create_server
    sockinfo=sockinfo,
  File "/usr/local/lib/python3.7/dist-packages/waitress/server.py", line 239, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.7/dist-packages/waitress/server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.7/dist-packages/waitress/wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use

Can anyone help?

**Comment by youngwoo-yoon** [comment]
Maybe another process is already using the port 8080. Please try another port (for example, 8888 instead of 8080).

**Comment by ireneb612** [comment]
@youngwoo-yoon  thank you I will try!

**Comment by ireneb612** [comment]
@youngwoo-yoon  So I tried this aproach and it seemed to work since it did not give me any error, but then when I tried to go to **http://0.0.0.0:8888/** 
I got this error:  ERR_ADDRESS_INVALID.

Do you know how I could deal?

**Comment by youngwoo-yoon** [comment]
Do you see the console output saying "Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)"? If you do, I guess it should work. Could you try 127.0.0.1:8888?

**Comment by ireneb612** [comment]
I get this:

loading checkpoint /content/drive/MyDrive/Gesture-Generation-from-Trimodal-Context/SGToolkit/sg_core/output/sgtoolkit/multimodal_context_checkpoint_best.bin
{'config': '../config/multimodal_context_toolkit.yml', 'name': 'multimodal_context', 'train_data_path': '../data/ted_dataset_2020.07/lmdb_train', 'val_data_path': '../data/ted_dataset_2020.07/lmdb_val', 'test_data_path': '../data/ted_dataset_2020.07/lmdb_test', 'model_save_path': '../output/temp', 'pose_representation': '3d_vec', 'pose_norm_stats_path': None, 'pose_representation_path': None, 'mean_dir_vec': [[-0.00225], [-0.98496], [0.16212], [0.01831], [-0.79641], [0.52568], [0.02496], [-0.65216], [-0.67807], [-0.87815], [0.40211], [-0.06526], [-0.38831], [0.85245], [0.13283], [0.35888], [-0.16606], [0.7072], [0.87728], [0.41491], [-0.00166], [0.38441], [0.85739], [0.14593], [-0.39277], [-0.17973], [0.69081]], 'mean_pose': [[-0.0], [-2e-05], [4e-05], [-0.00055], [-0.24976], [0.03882], [0.00152], [-0.32251], [0.10291], [0.0043], [-0.43652], [0.02527], [-0.12537], [-0.19055], [0.03108], [-0.23547], [0.04413], [0.06726], [-0.14551], [0.00403], [0.23596], [0.12585], [-0.18445], [0.04031], [0.23547], [0.04749], [0.08014], [0.13293], [0.00299], [0.24744]], 'style_val_max': [[0.01574225], [1.5461352], [1.0]], 'style_val_mean': [[0.00241791], [0.48645255], [0.0]], 'style_val_std': [[0.00120855], [0.17992376], [1.0]], 'random_seed': 0, 'save_result_video': True, 'wordembed_path': '../data/fasttext/crawl-300d-2M-subword.bin', 'wordembed_dim': 300, 'freeze_wordembed': False, 'model': 'multimodal_context', 'epochs': 80, 'batch_size': 128, 'dropout_prob': 0.3, 'n_layers': 4, 'hidden_size': 300, 'residual_output': False, 'z_type': 'style_vector', 'input_context': 'both', 'use_pose_control': True, 'use_style_control': True, 'motion_resampling_framerate': 15, 'n_poses': 60, 'n_pre_poses': 30, 'subdivision_stride': 20, 'normalize_motion_data': True, 'augment_data': False, 'loader_workers': 4, 'GAN_noise_size': 0, 'diff_augment': True, 'learning_rate': 0.0005, 'discriminator_lr_weight': 0.2, 'loss_l1_weight': 500.0, 'loss_gan_weight': 5.0, 'loss_reg_weight': 0.05, 'loss_warmup': 10, 'eval_net_path': '../output/h36m_gesture_autoencoder/gesture_autoencoder_checkpoint_best.bin'}
**Serving on http://0.0.0.0:8888/**

When I click I get that error, idk if it could be since i run it on colab ?!  I had to since I have Windows, maybe it would be interesting to have a docker version of it, but idk...
Also by typying  127.0.0.1:8888 i got another error that is about permission... maybe I could work on that.

**Comment by youngwoo-yoon** [comment]
I don't think this would run in Colab. I'm not completely sure, but you can try WSL (Windows Subsystem for Linux).

**Comment by ireneb612** [comment]
@youngwoo-yoon Hi I decided to try eith WLS! I managed to get to the local host but then when I try to generate audio fron a text:

(venv) irenetafani@LAPTOP-F0JUUKDE:~/SGToolkit$ python3.7 waitress_server.py
/home/irenetafani/SGToolkit/venv/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
loading checkpoint /home/irenetafani/SGToolkit/sg_core/output/sgtoolkit/multimodal_context_checkpoint_best.bin
{'config': '../config/multimodal_context_toolkit.yml', 'name': 'multimodal_context', 'train_data_path': '../data/ted_dataset_2020.07/lmdb_train', 'val_data_path': '../data/ted_dataset_2020.07/lmdb_val', 'test_data_path': '../data/ted_dataset_2020.07/lmdb_test', 'model_save_path': '../output/temp', 'pose_representation': '3d_vec', 'pose_norm_stats_path': None, 'pose_representation_path': None, 'mean_dir_vec': [[-0.00225], [-0.98496], [0.16212], [0.01831], [-0.79641], [0.52568], [0.02496], [-0.65216], [-0.67807], [-0.87815], [0.40211], [-0.06526], [-0.38831], [0.85245], [0.13283], [0.35888], [-0.16606], [0.7072], [0.87728], [0.41491], [-0.00166], [0.38441], [0.85739], [0.14593], [-0.39277], [-0.17973], [0.69081]], 'mean_pose': [[-0.0], [-2e-05], [4e-05], [-0.00055], [-0.24976], [0.03882], [0.00152], [-0.32251], [0.10291], [0.0043], [-0.43652], [0.02527], [-0.12537], [-0.19055], [0.03108], [-0.23547], [0.04413], [0.06726], [-0.14551], [0.00403], [0.23596], [0.12585], [-0.18445], [0.04031], [0.23547], [0.04749], [0.08014], [0.13293], [0.00299], [0.24744]], 'style_val_max': [[0.01574225], [1.5461352], [1.0]], 'style_val_mean': [[0.00241791], [0.48645255], [0.0]], 'style_val_std': [[0.00120855], [0.17992376], [1.0]], 'random_seed': 0, 'save_result_video': True, 'wordembed_path': '../data/fasttext/crawl-300d-2M-subword.bin', 'wordembed_dim': 300, 'freeze_wordembed': False, 'model': 'multimodal_context', 'epochs': 80, 'batch_size': 128, 'dropout_prob': 0.3, 'n_layers': 4, 'hidden_size': 300, 'residual_output': False, 'z_type': 'style_vector', 'input_context': 'both', 'use_pose_control': True, 'use_style_control': True, 'motion_resampling_framerate': 15, 'n_poses': 60, 'n_pre_poses': 30, 'subdivision_stride': 20, 'normalize_motion_data': True, 'augment_data': False, 'loader_workers': 4, 'GAN_noise_size': 0, 'diff_augment': True, 'learning_rate': 0.0005, 'discriminator_lr_weight': 0.2, 'loss_l1_weight': 500.0, 'loss_gan_weight': 5.0, 'loss_reg_weight': 0.05, 'loss_warmup': 10, 'eval_net_path': '../output/h36m_gesture_autoencoder/gesture_autoencoder_checkpoint_best.bin'}
--------------------------------------------
request time: 2022-02-28 15:43:49.975636
request IP: 127.0.0.1
Hello everybody my name is Irene and today I am going to talk about aliens and planets in the universe.
Hello everybody my name is Irene and today I am going to talk about aliens and planets in the universe
synthesis: took 0.86 seconds
written to file "./cached_wav/6073941519534249528.wav"
save wav file: took 0.00 seconds
ERROR:app:Exception on /api/input [POST]
Traceback (most recent call last):
  File "/home/irenetafani/SGToolkit/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/irenetafani/SGToolkit/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/irenetafani/SGToolkit/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/irenetafani/SGToolkit/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/irenetafani/SGToolkit/app.py", line 163, in input_text_post
    style_values=style_constraints, voice=content.get('voice'))
  File "/home/irenetafani/SGToolkit/sg_core/scripts/gesture_generator.py", line 86, in generate
    words_with_timestamps = self.align_words(audio, text_without_tags)
  File "/home/irenetafani/SGToolkit/sg_core/scripts/gesture_generator.py", line 51, in align_words
    conservative=False)
  File "/home/irenetafani/SGToolkit/gentle/gentle/forced_aligner.py", line 18, in __init__
    gen_hclg_filename = language_model.make_bigram_language_model(ks, resources.proto_langdir, **kwargs)
  File "/home/irenetafani/SGToolkit/gentle/gentle/language_model.py", line 126, in make_bigram_language_model
    raise e
  File "/home/irenetafani/SGToolkit/gentle/gentle/language_model.py", line 120, in make_bigram_language_model
    stderr=devnull)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ext/m3': 'ext/m3'
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1

I get this error...
