### ISSUE TITLE
invalid load key, 'v'

### ISSUE THREAD

**Issue by muyuelingxiao** [ai4r/SGToolkit#6]
![图片](https://user-images.githubusercontent.com/47098153/158383513-ed8d80ef-fcd6-4f09-9061-37f962256102.png)

I don't know how to solve it. Sincerely need help!

**Comment by youngwoo-yoon** [comment]
I think the checkpoint file is not correctly downloaded. Please download the checkpoint file manually on Github page here: https://github.com/ai4r/SGToolkit/tree/main/sg_core/output/sgtoolkit.

**Comment by muyuelingxiao** [comment]
It works. Thank u very much~
