### ISSUE TITLE
Generation issue

### ISSUE THREAD

**Issue by muyuelingxiao** [ai4r/SGToolkit#7]
When I connected to loacalhost:8080, the buttons have no responses. I can't know the sample text.
![图片](https://user-images.githubusercontent.com/47098153/158493391-a8c07e7f-d0b8-4d78-ad18-8f96753e1e40.png)
And the terminal has this output:
![图片](https://user-images.githubusercontent.com/47098153/158493458-36b04747-e17d-4b77-9136-ac7a9be968e2.png)
Should I wait for a period of time?

**Comment by muyuelingxiao** [comment]
Sorry, I just changed the network. Now it runs well.

**Comment by muyuelingxiao** [comment]
How long will generation take? When I used the sample text, the generation was loading all the time. Should I open other web, such as TTS?
![图片](https://user-images.githubusercontent.com/47098153/158495391-6f495141-254a-48eb-ab44-f6fd71beca8f.png)

**Comment by muyuelingxiao** [comment]
The error is as below.
![图片](https://user-images.githubusercontent.com/47098153/158502663-875b5ba1-2bcd-4491-84e1-3c57da481131.png)

**Comment by youngwoo-yoon** [comment]
Returning a dict object should be okay (see https://flask.palletsprojects.com/en/2.0.x/quickstart/#apis-with-json). Which Flask version do you use in your environment? Sorry that I didn't specify the Flask version in requirements.txt.

**Comment by muyuelingxiao** [comment]
My flask is 1.0.2. Thanks for your reply.

I'm dealing the issues with Google Cloud API. It's a little difficult.

I don't know why can't I upload the audio. Could you give me some suggestions?
![图片](https://user-images.githubusercontent.com/47098153/158564740-49230441-60d2-4787-a065-1315dbb77725.png)

**Comment by youngwoo-yoon** [comment]
Please use Flask 1.1.2 or higher. Flask supports returning dict objects since 1.1.0.

**Comment by youngwoo-yoon** [comment]
I never had problems in uploading wav files. I used Filepond library with input constraints `<input accept="audio/wav, audio/mp3" type="file" class="filepond">`
The comment in this issue (https://github.com/pqina/vue-filepond/issues/40) suggests to check MIME types. Please have a look.

**Comment by muyuelingxiao** [comment]
> Please use Flask 1.1.2 or higher. Flask supports returning dict objects since 1.1.0.

Yeh, now it works.

**Comment by muyuelingxiao** [comment]
> I never had problems in uploading wav files. I used Filepond library with input constraints `<input accept="audio/wav, audio/mp3" type="file" class="filepond">` The comment in this issue ([pqina/vue-filepond#40](https://github.com/pqina/vue-filepond/issues/40)) suggests to check MIME types. Please have a look.

![图片](https://user-images.githubusercontent.com/47098153/158573896-ec941186-4522-44c8-a25b-4f456954fad8.png)
When I upload, there is no another choice for file types. Only "All files"

**Comment by youngwoo-yoon** [comment]
I mean that I suggest checking your wav file by inspecting MIME information (in other words, checking whether your file is in a correct wav format). Or you would try converting it to mp3 and loading mp3 file.
