### ISSUE TITLE
Blender scripts

### ISSUE THREAD

**Issue by muyuelingxiao** [ai4r/SGToolkit#8]
I am new to Blender. How can I run the script without errors? Now I can't find errors. Only the messages on the bottom left.
![图片](https://user-images.githubusercontent.com/47098153/159432717-58b406ae-a91d-4ecb-8f6d-ddded095c44f.png)

**Comment by muyuelingxiao** [comment]
Do I have the right data path? The error seems the version mismatching. I am finding the solution.
![图片](https://user-images.githubusercontent.com/47098153/159443477-1dcefb57-715f-4e73-b246-1e429441b2d9.png)

**Comment by youngwoo-yoon** [comment]
Hello, 
If I remember correctly, you need to run blender on the path containing data folder. 
Or you could specify `data_folder` variable to be an absolute path.

**Comment by muyuelingxiao** [comment]
Thanks for advice.
I chose the first method. Then got this message, does it mean the json file has wrong format?
![图片](https://user-images.githubusercontent.com/47098153/159447098-c7f84095-374f-4fa3-9e24-72fbe77ed39c.png)

**Comment by muyuelingxiao** [comment]
Maybe I choose the wrong file. I will check the file. Thank you very very much.

**Comment by muyuelingxiao** [comment]
Now it works. I am so happy to run successfully. I am still a student and this is one part of my future research. I really admire your research achievements in this area.

**Comment by youngwoo-yoon** [comment]
Awesome! Thank you for your interest in our work and I'm also looking forward to your work.
