### ISSUE TITLE
Code testing

### ISSUE THREAD

**Issue by muyuelingxiao** [ai4r/SGToolkit#9]
Hello~

Now I want to change the network for own testings. I am not sure that the way of encoding audio will change when I modify the structure of  'Class WavEncoder' in 'multimodal_context_net.py'. Because I didn't find where the 'WavEncoder' is used. This is a little different from code "Gesture Generation from Trimodal Context".

Hope your reply!  :D

**Comment by youngwoo-yoon** [comment]
I think you missed this line https://github.com/ai4r/SGToolkit/blob/4245a788fa921ba00631a9936c42942eb2a5f89f/sg_core/scripts/model/multimodal_context_net.py#L134
PoseGenerator is using WavEncoder to encode audio data.

**Comment by muyuelingxiao** [comment]
Thanks for your patient explanation. I find the correct place. :D
